# Token to run the bot with
token: "PUT_BOT_TOKEN_HERE"

# Database to use for BotCommands dependency (THIS IS NOT FOR THE BOTS DATA)
# Supports: MariaDB, SQLite, PostgreSQL, H2
database: "PUT_CONNECTION_STRING_HERE"

# The Mongo database connection string to store data for the bot
mongo: "PUT_CONNECTION_STRING_HERE"

# Owner IDs of the bot
owners:
  primary: 242385234992037888 # srnyx
  other:
    - 273538684526264320 # ChrizxzFTW
    - 533985117589471233 # Reece

# Settings regarding the main guild for the bot (support server)
guild:
  # The ID of the guild
  id: 879734848946847774
  # Log channel for global actions (super punishments, etc...)
  log: 1008889846850408489

# Rotating status messages for the bot
statuses:
  - "watching %servers% servers"
  - "watching %users% total users"
  - "watching %unique_users% unique users"
  - "watching over srnyx.com/discord"
  - "watching over discord.gg/commandgeek"
  - "watching over discord.gg/skeppy"
  - "watching over venox.network"
  - "watching over charged.venox.network"
  - "watching over eventalerts.gg"
  - "watching over srnyx.com"
  - "watching over chrizxz.com"
  - "playing on charged.venox.network"
  - "playing on play.eventalerts.gg"
  - "listening to srnyx.com/playlist"
  - "listening to chrizxz.com/playlist"

# A list of questions to be used when a user joins a server
welcome-questions:
  - "Where are you from?"
  - "Who's your favorite content creator?"
  - "Who's your favorite superhero?"
  - "Who's your favorite super-villain?"
  - "Who's your favorite actor?"
  - "Who's your favorite singer/band?"
  - "What's your favorite video game?"
  - "What's your favorite movie?"
  - "What's your favorite TV show?"
  - "What's your favorite song?"
  - "What's your favorite food?"
  - "What's your favorite color?"
  - "What's your favorite animal?"
  - "What's your favorite sport?"
  - "What's your favorite hobby?"
  - "What's your favorite subject in school?"
  - "What's your favorite holiday?"
  - "What's your favorite season?"
  - "What's your favorite weather?"
  - "What's your favorite emoji?"
  - "What's your favorite meme?"
  - "What's your favorite video game?"
  - "What's your favorite video game console?"
  - "What's your favorite thing to do?"
